export const Icons = {
  TIFIN_LOGO: require('./tiffinwala-logo.png'),
  LeftArrow: require('./leftArrow.webp'),
  SEARCH: require('./search.webp'),
  MAP_PIN: require('./mapPin.webp'),
  FILTER: require('./filter.webp'),
  PROFILE: require('./user.png'),
  CALENDAR: require('./calendar.webp'),
  ORDER: require('./order.webp'),

  HELP_SUPPORT: require('./help.webp'),
  SHIELD: require('./shield.webp'),
  LOGOUT: require('./logout.webp'),
  BELL: require('./bell.webp'),
  TOGGLE_ON: require('./toggleOn.webp'),
  TOGGLE_OFF: require('./toggleOff.webp'),
  STAR_OUTLINE: require('./star_outline.webp'),
  STAR_FILLED: require('./star_filled.webp'),
  RIGHT_ARROW: require('./right_arrow.png'),
  CORRECT: require('./correct.png'),
  CAMERA: require('./camera.png'),

  CUTLERY: require('./cutlery.png'),
  MEAL: require('./dinner.png'),
  USERS: require('./users.png'),
  DASHBOARD: require('./dashboard.png'),
  RUPEE: require('./rupee.png'),
  RISE: require('./rise.png'),
  EDIT: require('./edit.png'),
  CLOSE: require('./close.png'),

  DELIVERY: require('./delivery.png'),
  SELF_PICKUP: require('./selfPickup.png'),
  MONTHLY: require('./monthly.png'),
  WEEKLY: require('./weekly.png'),
  TODAY: require('./today.png'),
};
